site_name: AI and ML Notes
theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/favicon.ico
  features:
    - navigation.instant
    - navigation.top
    - navigation.sections
  palette:
    scheme: default
    primary: custom

plugins:
  - mermaid2
  - search

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.arithmatex
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
      
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Patterns:
      - Overview: patterns/index.md
      - Glossary: patterns/glossary.md
      - Probability & Statistics: patterns/stats.md
  - Machine Learning:
      - Overview: ml/index.md
      - Bayesian Learning: ml/bayes_learning.md
      - Clustering: ml/clustering.md
      - Decision Trees: ml/decision_trees.md
      - Instance Based Learning: ml/instance_based.md
      - Neural Nets: ml/nn.md
      - Random Optimization: ml/rand_optim.md
      - SVM: ml/svm.md
  - NLP:
      - Overview: nlp/index.md
      - Distributional Semantics: nlp/distributional_semantics.md
  - Deep Learning:
      - Overview: dl/index.md
  - AI for Robotics:
      - Overview: robotics/index.md
  - Reinforcement Learning:
      - Overview: rl/index.md
      - Game Theory: rl/game_theory.md


      


